platform:ios, '5.0'
pod 'AFNetworking', '1.3.2'
pod 'SVProgressHUD', '0.9'
pod 'FMDB', '2.1'
pod 'AKTabBarController', '1.1.0'
pod 'REMenu', '1.4'
pod 'FlatUIKit', '1.2'
pod 'ASIHTTPRequest', '1.8.1'
pod 'MBProgressHUD', '0.7'
pod 'BlockAlertsAnd-ActionSheets', '1.0.6'
pod 'TTTAttributedLabel', '1.7.1'
pod 'SVHTTPRequest', '0.5'
pod 'SVWebViewController', '0.1'
pod 'EGOTableViewPullRefresh', '0.1.0'
pod 'SVPullToRefresh', '0.4.1'
pod 'JSMessagesViewController', '2.0.2'
pod 'SVPullToRefresh', '0.4.1'
pod 'EGOTableViewPullRefresh', '0.1.0'
pod 'CocoaAsyncSocket', '7.3.1'
pod 'SAMCache', '0.2.0'
pod 'TMCache', '1.2.0'
pod 'InfinitePagingView', '0.0.1'
pod 'PopoverView', '0.0.1'
pod 'FPPopover', '1.4.1'
pod 'SVSegmentedControl', '0.2'
pod 'KGStatusBar', '1.0'

